// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGwyVmlTwSKyU18Gaqwt22jKi6EGLAz_I',
    appId: '1:774182754397:web:3699937b9110a9072e55b4',
    messagingSenderId: '774182754397',
    projectId: 'andriod-d9c4b',
    authDomain: 'andriod-d9c4b.firebaseapp.com',
    storageBucket: 'andriod-d9c4b.firebasestorage.app',
    measurementId: 'G-N8N4Y2B136',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG17IsuZ9Od5H69a2KJfCwNuxxdgcBB1k',
    appId: '1:774182754397:android:03ba2d559ac6ec902e55b4',
    messagingSenderId: '774182754397',
    projectId: 'andriod-d9c4b',
    storageBucket: 'andriod-d9c4b.firebasestorage.app',
  );
}
